### PR TITLE
Update the upper bound for base

### PR DESCRIPTION
**Pull request by fumieval**

### CODE REVIEW

**Comment by peti** [comment]
Please apply this patch and release a new version. The current release of HTTP does not compile with GHC 8.4.1 purely because the metadata is out of date.

**Comment by hvr** [comment]
There's no release needed, all we need is a simple meta-data revision via http://hackage.haskell.org/package/HTTP-4000.3.9/HTTP.cabal/edit

**Comment by ndmitchell** [comment]
@hvr - can you (with your Trustee hat on 🎩) make that edit?

**Comment by hsenag** [comment]
Sorry, I wasn't actually ignoring this, I was just hoping to run the full test suite first, but the dependencies have some build problems. Given the official release is out I'll do an upload shortly and worry about the tests later.

**Comment by hsenag** [comment]
Released as 4000.3.10.

**Comment by hvr** [comment]
@hsenag btw, for the test-suite, you could have simply used https://github.com/hvr/head.hackage

And then you'd simply (the `streaming-commons < 0.2` constraint is needed to workaround bugs in `conduit-extra`'s meta-data)

```
$ cabal new-test -w ghc-8.4.1 --constraint 'streaming-commons < 0.2'
Resolving dependencies...
Build profile: -w ghc-8.4.1 -O1
In order, the following will be built (use -v for more details):
 - HTTP-4000.3.10 (lib) (first run)
 - HTTP-4000.3.10 (test:test) (first run)
Configuring library for HTTP-4000.3.10..
Preprocessing library for HTTP-4000.3.10..
Building library for HTTP-4000.3.10..
[ 1 of 18] Compiling Network.HTTP.Base64 ( Network/HTTP/Base64.hs, /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/build/Network/HTTP/Base64.o )
[ 2 of 18] Compiling Network.HTTP.MD5Aux ( Network/HTTP/MD5Aux.hs, /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/build/Network/HTTP/MD5Aux.o )
[ 3 of 18] Compiling Network.HTTP.Utils ( Network/HTTP/Utils.hs, /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/build/Network/HTTP/Utils.o )
[ 4 of 18] Compiling Network.BufferType ( Network/BufferType.hs, /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/build/Network/BufferType.o )
[ 5 of 18] Compiling Network.Stream   ( Network/Stream.hs, /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/build/Network/Stream.o )

Network/Stream.hs:35:1: warning: [-Wdeprecations]
    Module ‘Control.Monad.Error’ is deprecated:
      Use Control.Monad.Except instead
   |
35 | import Control.Monad.Error
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^

Network/Stream.hs:44:10: warning: [-Wdeprecations]
    In the use of type constructor or class ‘Error’
    (imported from Control.Monad.Error, but defined in transformers-0.5.5.0:Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"
   |
44 | instance Error ConnError where
   |          ^^^^^

Network/Stream.hs:44:10: warning: [-Wdeprecations]
    In the use of type constructor or class ‘Error’
    (imported from Control.Monad.Error, but defined in transformers-0.5.5.0:Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"
   |
44 | instance Error ConnError where
   |          ^^^^^

Network/Stream.hs:45:11: warning: [-Wdeprecations]
    In the use of ‘strMsg’
    (imported from Control.Monad.Error, but defined in transformers-0.5.5.0:Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"
   |
45 |   noMsg = strMsg "unknown error"
   |           ^^^^^^

Network/Stream.hs:52:24: warning: [-Wdeprecations]
    In the use of ‘strMsg’
    (imported from Control.Monad.Error, but defined in transformers-0.5.5.0:Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"
   |
52 | failMisc x = failWith (strMsg x)
   |                        ^^^^^^
[ 6 of 18] Compiling Network.HTTP.Headers ( Network/HTTP/Headers.hs, /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/build/Network/HTTP/Headers.o )
[ 7 of 18] Compiling Network.HTTP.Cookie ( Network/HTTP/Cookie.hs, /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/build/Network/HTTP/Cookie.o )
[ 8 of 18] Compiling Paths_HTTP       ( /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/build/autogen/Paths_HTTP.hs, /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/build/Paths_HTTP.o )
[ 9 of 18] Compiling Network.HTTP.Base ( Network/HTTP/Base.hs, /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/build/Network/HTTP/Base.o )

Network/HTTP/Base.hs:110:1: warning: [-Wdeprecations]
    Module ‘Control.Monad.Error’ is deprecated:
      Use Control.Monad.Except instead
    |
110 | import Control.Monad.Error ()
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[10 of 18] Compiling Network.TCP      ( Network/TCP.hs, /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/build/Network/TCP.o )

Network/TCP.hs:245:32: warning: [-Wdeprecations]
    In the use of ‘sClose’ (imported from Network.Socket):
    Deprecated: "use 'close'"
    |
245 |                             ) (sClose s)
    |                                ^^^^^^

Network/TCP.hs:298:5: warning: [-Wdeprecations]
    In the use of ‘sClose’ (imported from Network.Socket):
    Deprecated: "use 'close'"
    |
298 |     sClose sk
    |     ^^^^^^
[11 of 18] Compiling Network.StreamDebugger ( Network/StreamDebugger.hs, /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/build/Network/StreamDebugger.o )
[12 of 18] Compiling Network.StreamSocket ( Network/StreamSocket.hs, /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/build/Network/StreamSocket.o )

Network/StreamSocket.hs:53:21: warning: [-Wdeprecations]
    In the use of ‘recv’ (imported from Network.Socket):
    "Use recv defined in "Network.Socket.ByteString""
   |
53 |         in catchIO (recv sock len) handler
   |                     ^^^^

Network/StreamSocket.hs:62:10: warning: [-Wdeprecations]
    In the use of ‘sClose’ (imported from Network.Socket):
    Deprecated: "use 'close'"
   |
62 |          sClose sk
   |          ^^^^^^

Network/StreamSocket.hs:92:12: warning: [-Wdeprecations]
    In the use of ‘send’ (imported from Network.Socket):
    "Use send defined in "Network.Socket.ByteString""
   |
92 |    fn x  = send sk x >>= \i -> fn (drop i x)
   |            ^^^^
[13 of 18] Compiling Network.HTTP.Stream ( Network/HTTP/Stream.hs, /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/build/Network/HTTP/Stream.o )
[14 of 18] Compiling Network.HTTP.HandleStream ( Network/HTTP/HandleStream.hs, /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/build/Network/HTTP/HandleStream.o )
[15 of 18] Compiling Network.HTTP.Auth ( Network/HTTP/Auth.hs, /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/build/Network/HTTP/Auth.o )
[16 of 18] Compiling Network.HTTP.Proxy ( Network/HTTP/Proxy.hs, /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/build/Network/HTTP/Proxy.o )
[17 of 18] Compiling Network.HTTP     ( Network/HTTP.hs, /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/build/Network/HTTP.o )
[18 of 18] Compiling Network.Browser  ( Network/Browser.hs, /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/build/Network/Browser.o )
Configuring test suite 'test' for HTTP-4000.3.10..
Warning: The package has an extraneous version range for a dependency on an internal library: HTTP -any && ==4000.3.10. This version range includes the current package but isn't needed as the current package's library will always be used.
Preprocessing test suite 'test' for HTTP-4000.3.10..
Building test suite 'test' for HTTP-4000.3.10..
[1 of 3] Compiling Httpd            ( test/Httpd.hs, /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/t/test/build/test/test-tmp/Httpd.o )
[2 of 3] Compiling UnitTests        ( test/UnitTests.hs, /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/t/test/build/test/test-tmp/UnitTests.o )
[3 of 3] Compiling Main             ( test/httpTests.hs, /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/t/test/build/test/test-tmp/Main.o )
Linking /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/t/test/build/test/test ...
Running 1 test suites...
Test suite test: RUNNING...
Unit tests:
  URI parsing:
    Parse IPv4 address: [OK]
    Parse IPv6 address: [OK]
httpd-shed:
  Basic tests:
    Basic GET request: [OK]
    Basic GET request (lazy bytestring): [OK]
    Network.HTTP example code: [OK]
    Secure GET request: [OK]
    Basic POST request: [OK]
    Basic HEAD request: [OK]
    URI user:pass Auth failure: [OK]
    URI user:pass Auth success: [OK]
    Basic Auth failure: [OK]
    Basic Auth success: [OK]
    UTF-8 urlEncode: [OK]
    UTF-8 urlDecode: [OK]
  Browser tests:
    Basic:
Sending:
GET /browser/example HTTP/1.1
Host: 127.0.0.1:5812
Content-Length: 0
User-Agent: haskell-HTTP/4000.3.10


Creating new connection to 127.0.0.1:5812
Received:
HTTP/1.1 200 OK 
Connection: close
Content-Length: 549


      Network.Browser example code: [OK]
      Two requests: [OK]
    Secure:
      Secure request: [OK]
      After insecure: [OK]
      Redirection: [OK]
    Cookies:
      No cookie header: [OK]
      One cookie: [OK]
      Two cookies: [OK]
    Redirection:
      300: [OK]
      301: [OK]
      302: [OK]
      303: [OK]
      304: [OK]
      307: [OK]
      308: [OK]
    Authentication:
      Basic: [OK]
      Digest: [OK]
warp.v6:
  Basic tests:
    Basic GET request: [OK]
    Basic GET request (lazy bytestring): [OK]
    Network.HTTP example code: [OK]
    Secure GET request: [OK]
    Basic POST request: [OK]
    Basic HEAD request: [OK]
    URI user:pass Auth failure: [OK]
    URI user:pass Auth success: [OK]
    Basic Auth failure: [OK]
    Basic Auth success: [OK]
    UTF-8 urlEncode: [OK]
    UTF-8 urlDecode: [OK]
  Browser tests:
    Basic:
Sending:
GET /browser/example HTTP/1.1
Host: [::1]:5813
Content-Length: 0
User-Agent: haskell-HTTP/4000.3.10


Creating new connection to [::1]:5813
Received:
HTTP/1.1 200 
Transfer-Encoding: chunked
Date: Sat, 10 Mar 2018 07:37:18 GMT
Server: Warp/3.2.18
Content-Length: 549


      Network.Browser example code: [OK]
      Two requests: [OK]
    Secure:
      Secure request: [OK]
      After insecure: [OK]
      Redirection: [OK]
    Cookies:
      No cookie header: [OK]
      One cookie: [OK]
      Two cookies: [OK]
    Redirection:
      300: [OK]
      301: [OK]
      302: [OK]
      303: [OK]
      304: [OK]
      307: [OK]
      308: [OK]
    Authentication:
      Basic: [OK]
      Digest: [OK]
warp.v4:
  Basic tests:
    Basic GET request: [OK]
    Basic GET request (lazy bytestring): [OK]
    Network.HTTP example code: [OK]
    Secure GET request: [OK]
    Basic POST request: [OK]
    Basic HEAD request: [OK]
    URI user:pass Auth failure: [OK]
    URI user:pass Auth success: [OK]
    Basic Auth failure: [OK]
    Basic Auth success: [OK]
    UTF-8 urlEncode: [OK]
    UTF-8 urlDecode: [OK]
  Browser tests:
    Basic:
Sending:
GET /browser/example HTTP/1.1
Host: 127.0.0.1:5814
Content-Length: 0
User-Agent: haskell-HTTP/4000.3.10


Creating new connection to 127.0.0.1:5814
Received:
HTTP/1.1 200 
Transfer-Encoding: chunked
Date: Sat, 10 Mar 2018 07:37:18 GMT
Server: Warp/3.2.18
Content-Length: 549


      Network.Browser example code: [OK]
      Two requests: [OK]
    Secure:
      Secure request: [OK]
      After insecure: [OK]
      Redirection: [OK]
    Cookies:
      No cookie header: [OK]
      One cookie: [OK]
      Two cookies: [OK]
    Redirection:
      300: [OK]
      301: [OK]
      302: [OK]
      303: [OK]
      304: [OK]
      307: [OK]
      308: [OK]
    Authentication:
      Basic: [OK]
      Digest: [OK]

         Test Cases   Total       
 Passed  89           89          
 Failed  0            0           
 Total   89           89          
Test suite test: PASS
Test suite logged to: /tmp/HTTP-4000.3.10/dist-newstyle/build/x86_64-linux/ghc-8.4.1/HTTP-4000.3.10/t/test/test/HTTP-4000.3.10-test.log
1 of 1 test suites (1 of 1 test cases) passed.
```

**Comment by hsenag** [comment]
I tried head.hackage, but at the time didn't realise what was going on with conduit-extra and gave up. Later I figured out the conduit-extra problem too when it broke with earlier ghcs, but didn't connect it back to my earlier problem :-)

**Comment by hsenag** [comment]
@hvr Sure, in principle (and I've done so this time as you know), but it's extra work to be sure what the problem is and report it, so I don't always have a chance to do it immediately.

**Pull request merged**
