### PR TITLE
Bump CI to ubuntu-20.04 and GHCs 9.6.1 9.4.4 9.2.7 9.0.2

### PR DESCRIPTION
**Pull request by andreasabel**
ubuntu-18.04 has reached EOL

### CODE REVIEW

**Comment by andreasabel** [comment]
CI succeeds @hsenag

**Comment by hsenag** [comment]
I actually looked at doing this a week or two ago and was a bit put off by https://github.com/haskell-CI/haskell-ci/issues/634 - but if you think it's ok I'm happy to go ahead with it.

**Comment by andreasabel** [comment]
@hsenag wrote:
> was a bit put off by [haskell-CI/haskell-ci#634](https://github.com/haskell-CI/haskell-ci/issues/634)

`haskell-ci` is very well maintained, but you have to use the `master` as it is not frequently released.  I update my `haskell-ci` installation basically every month, to get the latest GHC releases and prereleases.
So if you ask me, yes, I think it is ok.

Atm, there is little choice but to update, because the `ubuntu-18.04` virtual environment will be discontinued on 1st April.  Yes, that is in 3 days.  `haskell-ci` switched to `ubuntu-20.04` in May last year.
- https://github.com/actions/runner-images/issues/6002
- https://github.com/haskell-CI/haskell-ci/commit/656619d68604ab7aad0625f9e6df2d848fc510a6

Final word: I think the problem is not with `haskell-ci`, but `cabal` which is badly understaffed while incredibly complex; so bug are introduced.  However, if we want to support the latest GHCs, which everyone expects, we also have to live with recent versions of `cabal` which can talk to the latest GHCs.

**Comment by hsenag** [comment]
> haskell-ci is very well maintained, but you have to use the master as it is not frequently released. I update my haskell-ci installation basically every month, to get the latest GHC releases and prereleases.
So if you ask me, yes, I think it is ok.

I was more put off by the fact that the actual maintainer thinks it's broken. But I take your point about the balance of risks :-)

**Pull request merged**
