### PR TITLE
Allow network 2.7

### PR DESCRIPTION
**Pull request by felixonmars**
Builds fine and all tests pass here.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Looks like we need to constrain `resourcet` to < 1.2 on GHC == 7.10.*. Not sure why the solver can't figure it out automatically. Also it looks like `process-1.6.3.0` doesn't build with GHC 7.8.

**Comment by hsenag** [comment]
The process build failure on GHC 7.8 is Windows specific, I'll try to organise a fix for that if noone else gets there first. For the resourcet thing I'm thinking of simplifying the tests to not rely on the warp stack, it adds a lot of dependency complexity for marginal benefit.

**Comment by 23Skidoo** [comment]
I filed a ticket for the `process` bug: https://github.com/haskell/process/issues/131.

**Comment by 23Skidoo** [comment]
@hsenag Would be nice if you could also relax the dependency on Hackage or make a new minor release.

**Comment by hsenag** [comment]
Working on it, just want to bump the Win32 dependency too first

**Comment by 23Skidoo** [comment]
Great, thanks!

**Comment by hsenag** [comment]
Now done, sorry for being slow.

**Pull request merged**
