### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by hsenag** [comment]
Doesn't supporting network-3.0 also need some code changes? https://github.com/haskell/HTTP/pull/111 has them but some of the test dependencies (notably httpd-shed which I also maintain) need to be fixed.

**Comment by phadej** [comment]
@hsenag the change in #111 removes some warnings, but HTTP doesn't build warning free, so i didn't even notice it at first.

**Comment by phadej** [comment]
Windows failures are due `entropy` not building on windows :(

**Comment by phadej** [comment]
The last commit highlights, that maybe HTTP is up to larger refactoring using `ByteString` instead of `String`

**Comment by hsenag** [comment]
I looked at refactoring HTTP by overloading it on the string type a while ago, but it looked quite painful.

**Comment by hsenag** [comment]
Did you test the Win32 bump? I think [regQueryValue](http://hackage.haskell.org/package/Win32-2.7.0.0/docs/System-Win32-Registry.html#v:regQueryValue) has (changed type)[http://hackage.haskell.org/package/Win32-2.8.0.0/docs/System-Win32-Registry.html#v:regQueryValue] (again)[https://github.com/haskell/HTTP/blob/master/Network/HTTP/Proxy.hs#L106], but it seems to be part of a [refactoring](https://github.com/haskell/win32/commit/1c46705d72341ac608c58f29b61ceadcca7c7440) where actually it's changing name and something else is getting its name, so I need to check what the right thing to do is.

**Comment by hsenag** [comment]
If I just bump the `network` dependency I get this:

    $ cabal new-build --constraint 'network>=3.0' --disable-tests
 (..)

    Network/TCP.hs:41:6: error:
        Module ‘Network.Socket’ does not export ‘sClose’
       |
    41 |    , sClose, setSocketOption, getPeerName
       |      ^^^^^^

I plan to merge #111 but need to check what it means for lower bounds as well as sorting out the tests. Is anyone in a rush for this?

**Comment by phadej** [comment]
hackage-security repository have packages which depend on HTTP, so transitively this prevents from updating `cabal-install`; not big issue, but an issue.

cc @hvr

**Comment by phadej** [comment]
@hsenag are you sure you tried to build with **this** branch?

**Comment by hsenag** [comment]
I haven't used your branch itself, I was just saying that only bumping the `network` dependency isn't enough without the changes from #111. But we have those, so it's not a problem, I was just a bit confused about [your earlier comment](https://github.com/haskell/HTTP/pull/122#issuecomment-468168214).

For the Win32 changes, are you sure that `regQueryValue` is still the right thing to use given there's actually been some renaming going on?

**Comment by phadej** [comment]
I added GHC-8.4 and GHC-8.6 jobs to appveyor, let's see. I don't have windows box to try locally.

**Comment by hsenag** [comment]
It'll probably build and pass the tests, as there isn't anything about getting a proxy from the registry in them, but I don't think that would mean it's automatically ok.

**Comment by phadej** [comment]
a type change would cause a compile-error. But I cannot comment beyond that, I'm not familiar with windows

**Comment by phadej** [comment]
travis and appveyor are green

**Comment by Mistuke** [comment]
`regQueryDefaultValue` and `regQueryValue` are mostly the same, the only difference being that `regQueryDefaultValue` ensures the value is a `REG_SZ`. e.g. prevents you from reading a wrong registry type as string.

for a `1-1` mapping you should use `regQueryDefaultValue`, but functionally they are the same as long as the key is a `REG_SZ`.

**Comment by phadej** [comment]
@Mistuke so you advice using `regQueryDefaultValue` with Win32-2.8 (where it was introduced)? Where can I check if that key is `REG_SZ` or not?

**Comment by phadej** [comment]
... that key is
```haskell
    hive  = hKEY_CURRENT_USER
    path = "Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings"
```

**Comment by Mistuke** [comment]
> @Mistuke so you advice using regQueryDefaultValue with Win32-2.8 (where it was introduced).

Yup, that is a `1-1` mapping, the old `regQueryValue` was renamed to that.

> Where can I check if that key is REG_SZ or not?

You can view the type in the registry using regedit,or the following powershell script

```
$key = Get-Item -Path "Registry::HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings"
$key.GetValueNames() |
ForEach-Object {
	$name = $_
	$rv = 1 | Select-Object -Property Name, Type, Value
	$rv.Name = $name
	$rv.Type = $key.GetValueKind($name)
	$rv.Value = $key.GetValue($name)
	$rv

}
```

https://blogs.msdn.microsoft.com/askie/2015/10/12/how-to-configure-proxy-settings-for-ie10-and-ie11-as-iem-is-not-available/ seems to indicate that it is a `REG_SZ`.

**Comment by phadej** [comment]
@Mistuke I don't have Windows :( I even forgot a password to my virtual one (duh).

**Comment by Mistuke** [comment]
hehe, I don't currently have a proxy setup so the key doesn't exist, but the link above and some KB articles suggest it is a `REG_SZ`, which it must have been since you would have gotten an assert in the Win32 pre 2.8. 

So the change is fine, if you want to keep the failure in case the key ever changes (unlikely) you can use `regQueryDefaultValue`.

**Comment by phadej** [comment]
@Mistuke thanks for the info. I decided to use `regQueryDefaultValue`, let's see if appveyor is happy with `#ifdef`s.

**Comment by phadej** [comment]
The build is green.

@hsenag how the patch looks now?

**Comment by hsenag** [comment]
I don't think Travis and Appveyor cover any of the edge cases and as usual my own local testing environments have rotted since I last tested HTTP :-/

So far what I've spotted is:
- [ ] `network` lower bound doesn't seem to be correct yet, building with network 2.3 fails
- [ ] Can't build the tests with network-3.0 - I/someone needs to fix `httpd-shed`
- [ ] I need to install GHC 8.6 on Windows so I can test with Win32 2.8 - it has a build error with GHC 8.2

For the network lower bound, I tried ```cabal new-build --constraint 'network<2.4'``` with GHC 7.8 and got
```
Network/TCP.hs:47:6:
    Module ‘Network.Socket’ does not export ‘close’
```

**Comment by Mistuke** [comment]
Win32 shouldn't have a build error with 8.2, CI is all green https://ci.appveyor.com/project/hvr/win32  , do you happen to know what the error is?

Also network 3.0 is broken on Windows until the next release.

**Comment by hsenag** [comment]
Win32-2.8 worked fine for me with GHC 8.6.

@Mistuke I'll double-check the error and let you know. Thanks for your help with this btw!

**Comment by hsenag** [comment]
I can't reproduce the error with Win32-2.8 and now I've lost my scrollback, but now I get something similar with Win32-2.7 and GHC 8.6:

```
[31 of 65] Compiling System.Win32.Encoding ( System\Win32\Encoding.hs, dist\build\System\Win32\Encoding.o )

System\Win32\Encoding.hs:98:21: error:
    Variable not in scope:
      stringToUnicode :: CodePage -> String -> IO String
   |
98 | decodeMultiByteIO = stringToUnicode
   |                     ^^^^^^^^^^^^^^^
cabal.exe: Failed to build Win32-2.7.0.0 (which is required by test:test from
HTTP-4000.3.13).
```
I'll dig more into it later if the reason isn't obvious.

**Comment by Mistuke** [comment]
Hmm no that doesn't look familiar to me. It should be provided by `NLS`. I'll try to reproduce it. I'm assuming you're building this PR with GHC 8.6? Do you have the cabal invocation I can use?

**Comment by hsenag** [comment]
This was the specific command-line I used to get the message above, but I suspect triggering it is dependent on more factors like my local package DB/specific version of the hackage index/other things. 

Aargh, and now this one also worked when I just reran it (literally up-enter)!

There must be something funny about my machine/cabal setup, but no idea what...I'll try to debug more this evening.

```cabal new-build --enable-tests --constraint 'Win32>=2.7 && <2.8' --with-ghc='C:\ProgramData\chocolatey\lib\ghc.8.6.2\tools\ghc-8.6.2\bin\ghc'```

**Comment by hsenag** [comment]
@phadej thanks, the new lower bound looks good. It does probably mean that some other lower bounds (like base) are no longer actually attainable but it'd take some time to figure out precisely what the new lower bound should be and I think we can do that later. (@hvr, could that cause a problem?)

I'll try to sort out httpd-shed in the next couple of days.

**Comment by phadej** [comment]
`base >= 4.3.0.0 ` is definitely attainable.

```
[FL973] ~/Documents/other-haskell/HTTP update-deps % cabal new-build -w ghc-7.0.4 --constraint='network==2.4.*'
Resolving dependencies...
Build profile: -w ghc-7.0.4 -O1
In order, the following will be built (use -v for more details):
 - HTTP-4000.3.13 (lib) (first run)
Configuring library for HTTP-4000.3.13..
Preprocessing library for HTTP-4000.3.13..
Building library for HTTP-4000.3.13..
[ 1 of 18] Compiling Network.HTTP.MD5Aux ( Network/HTTP/MD5Aux.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/HTTP/MD5Aux.o )
[ 2 of 18] Compiling Paths_HTTP       ( /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/autogen/Paths_HTTP.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Paths_HTTP.o )
[ 3 of 18] Compiling Network.HTTP.Base64 ( Network/HTTP/Base64.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/HTTP/Base64.o )
[ 4 of 18] Compiling Network.Stream   ( Network/Stream.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/Stream.o )

Network/Stream.hs:35:1:
    Warning: Module `Control.Monad.Error' is deprecated:
               Use "Control.Monad.Except" instead

Network/Stream.hs:35:1:
    Warning: In the use of type constructor or class `Error'
             (imported from Control.Monad.Error, but defined in transformers-0.5.6.2:Control.Monad.Trans.Error):
             Deprecated: "Use Control.Monad.Trans.Except instead"

Network/Stream.hs:35:1:
    Warning: In the use of `noMsg'
             (imported from Control.Monad.Error, but defined in transformers-0.5.6.2:Control.Monad.Trans.Error):
             Deprecated: "Use Control.Monad.Trans.Except instead"

Network/Stream.hs:35:1:
    Warning: In the use of `strMsg'
             (imported from Control.Monad.Error, but defined in transformers-0.5.6.2:Control.Monad.Trans.Error):
             Deprecated: "Use Control.Monad.Trans.Except instead"
[ 5 of 18] Compiling Network.HTTP.Utils ( Network/HTTP/Utils.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/HTTP/Utils.o )
[ 6 of 18] Compiling Network.HTTP.Headers ( Network/HTTP/Headers.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/HTTP/Headers.o )
[ 7 of 18] Compiling Network.HTTP.Cookie ( Network/HTTP/Cookie.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/HTTP/Cookie.o )
[ 8 of 18] Compiling Network.BufferType ( Network/BufferType.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/BufferType.o )
[ 9 of 18] Compiling Network.HTTP.Base ( Network/HTTP/Base.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/HTTP/Base.o )
[10 of 18] Compiling Network.TCP      ( Network/TCP.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/TCP.o )
[11 of 18] Compiling Network.StreamDebugger ( Network/StreamDebugger.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/StreamDebugger.o )
[12 of 18] Compiling Network.StreamSocket ( Network/StreamSocket.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/StreamSocket.o )
[13 of 18] Compiling Network.HTTP.Auth ( Network/HTTP/Auth.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/HTTP/Auth.o )
[14 of 18] Compiling Network.HTTP.Proxy ( Network/HTTP/Proxy.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/HTTP/Proxy.o )
[15 of 18] Compiling Network.HTTP.HandleStream ( Network/HTTP/HandleStream.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/HTTP/HandleStream.o )
[16 of 18] Compiling Network.HTTP     ( Network/HTTP.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/HTTP.o )
[17 of 18] Compiling Network.HTTP.Stream ( Network/HTTP/Stream.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/HTTP/Stream.o )
[18 of 18] Compiling Network.Browser  ( Network/Browser.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/Browser.o )
[FL973] ~/Documents/other-haskell/HTTP update-deps % cabal-plan topo                                           
HTTP-4000.3.13 test:test
test-framework-hunit-0.3.0.2
extensible-exceptions-0.1.1.2
test-framework-0.8.2.0
xml-1.3.14
semigroups-0.18.5
unordered-containers-0.2.8.0
nats-1.1.2
hashable-1.2.5.0
regex-posix-0.95.2
regex-base-0.93.2
random-1.0.0.3
hostname-1.0
base-orphans-0.8
ansi-wl-pprint-0.6.7.3
ansi-terminal-0.6.3.1
split-0.2.3.3
pureMD5-2.1.3
crypto-api-0.13.2
tagged-0.8.6
transformers-compat-0.6.2
generic-deriving-1.12.3
th-abstraction-0.2.11.0
template-haskell-2.5.0.0
entropy-0.3.8 lib:entropy setup
cereal-0.4.1.1
httpd-shed-0.4.0.3
network-uri-2.5.0.0
HUnit-1.3.1.2
HTTP-4000.3.13
network-2.4.2.3
parsec-3.1.11
text-1.2.3.1
bytestring-builder-0.10.8.2.0
deepseq-1.4.2.0
binary-0.8.2.1
mtl-2.2.2
transformers-0.5.6.2
Cabal-1.20.0.4
time-1.2.0.3
process-1.0.1.5
pretty-1.0.1.2
directory-1.1.0.0
unix-2.4.2.0
old-time-1.0.0.6
old-locale-1.0.0.2
filepath-1.2.0.0
deepseq-1.3.0.2
containers-0.4.0.0
bytestring-0.9.1.10
array-0.3.0.2
base-4.3.1.0
integer-gmp-0.2.0.3
ghc-prim-0.2.0.0
rts-1.0
ffi-1.0
```

**Comment by phadej** [comment]
And in fact with `network-2.6` there are no problems with GHC-7.0 either

```
[FL973] ~/Documents/other-haskell/HTTP update-deps % cabal new-build -w ghc-7.0.4 --constraint='network==2.6.*'
Resolving dependencies...
Build profile: -w ghc-7.0.4 -O1
In order, the following will be built (use -v for more details):
 - HTTP-4000.3.13 (lib) (configuration changed)
Configuring library for HTTP-4000.3.13..
Preprocessing library for HTTP-4000.3.13..
Building library for HTTP-4000.3.13..
[ 9 of 18] Compiling Network.HTTP.Base ( Network/HTTP/Base.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/HTTP/Base.o )
[10 of 18] Compiling Network.TCP      ( Network/TCP.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/TCP.o )
[11 of 18] Compiling Network.StreamDebugger ( Network/StreamDebugger.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/StreamDebugger.o )
[12 of 18] Compiling Network.StreamSocket ( Network/StreamSocket.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/StreamSocket.o )
[13 of 18] Compiling Network.HTTP.Auth ( Network/HTTP/Auth.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/HTTP/Auth.o )
[14 of 18] Compiling Network.HTTP.Proxy ( Network/HTTP/Proxy.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/HTTP/Proxy.o )
[15 of 18] Compiling Network.HTTP.HandleStream ( Network/HTTP/HandleStream.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/HTTP/HandleStream.o )
[16 of 18] Compiling Network.HTTP     ( Network/HTTP.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/HTTP.o )
[17 of 18] Compiling Network.HTTP.Stream ( Network/HTTP/Stream.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/HTTP/Stream.o )
[18 of 18] Compiling Network.Browser  ( Network/Browser.hs, /home/ogre/Documents/other-haskell/HTTP/dist-newstyle/build/x86_64-linux/ghc-7.0.4/HTTP-4000.3.13/build/Network/Browser.o )
[FL973] ~/Documents/other-haskell/HTTP update-deps % cabal-plan topo                                           
HTTP-4000.3.13 test:test
test-framework-hunit-0.3.0.2
extensible-exceptions-0.1.1.2
test-framework-0.8.2.0
xml-1.3.14
semigroups-0.18.5
unordered-containers-0.2.8.0
nats-1.1.2
hashable-1.2.5.0
regex-posix-0.95.2
regex-base-0.93.2
random-1.0.0.3
hostname-1.0
base-orphans-0.8
ansi-wl-pprint-0.6.7.3
ansi-terminal-0.6.3.1
split-0.2.3.3
pureMD5-2.1.3
crypto-api-0.13.2
tagged-0.8.6
transformers-compat-0.6.2
generic-deriving-1.12.3
th-abstraction-0.2.11.0
template-haskell-2.5.0.0
entropy-0.3.8 lib:entropy setup
cereal-0.4.1.1
httpd-shed-0.4.0.3
HUnit-1.3.1.2
HTTP-4000.3.13
network-uri-2.6.1.0
parsec-3.1.11
text-1.2.3.1
bytestring-builder-0.10.8.2.0
binary-0.8.2.1
deepseq-1.4.2.0
network-2.6.3.1
mtl-2.2.2
transformers-0.5.6.2
Cabal-1.20.0.4
time-1.2.0.3
process-1.0.1.5
pretty-1.0.1.2
directory-1.1.0.0
unix-2.4.2.0
old-time-1.0.0.6
old-locale-1.0.0.2
filepath-1.2.0.0
deepseq-1.3.0.2
containers-0.4.0.0
bytestring-0.9.1.10
array-0.3.0.2
base-4.3.1.0
integer-gmp-0.2.0.3
ghc-prim-0.2.0.0
rts-1.0
ffi-1.0
```

**Comment by hsenag** [comment]
@Mistuke FYI my problems building Win32 seem to be that hsc2hs occasionally leaves a half-written file which then causes errors like the above later on. I'm guessing it's aborting for some reason but haven't caught it in the act. Anyway, definitely not a Win32 problem.

**Comment by Mistuke** [comment]
Aahh OK, that makes sense. Thanks for debugging! Could it be an old version
of hsc2hs? Or is hsc2hs being build from source as well?

**Comment by hsenag** [comment]
@phadej: Thanks for sorting all this out! I think bumping the lower bound to 2.6 is a good idea for longer-term maintenance. For now I've pushed what we have so far and released it to unblock anyone waiting for network-3.0.

@Mistuke: it's the hsc2hs with Haskell Platform 8.2.2. I may investigate in more detail later, or just upgrade my global GHC. Windows is always a painful platform to manage installations on and I still haven't really got the hang of using chocolatey.

**Comment by Mistuke** [comment]
@hsenag I manage the Chocolatey packages as well, so if there's anything I can do to make it easier for people to use I'm all ears.

Note that the next cabal release will come with an updated chocolatey package which will allow it to automate detection of msys2. This is already available on the nightlies.

**Pull request merged**
