### PR TITLE
Add a note that recommends alternative packages which support HTTPS

### PR DESCRIPTION
**Pull request by sjakobi**
See #105.

### CODE REVIEW

**Comment by sjakobi** [comment]
Thanks! Would you mind making a release (or revision) too, so the warning becomes visible?

**Comment by hsenag** [comment]
Done (along with a suggestion from @hvr), though the markdown doesn't work on hackage so it looks a bit messed up :-( http://hackage.haskell.org/package/HTTP

**Comment by hvr** [comment]
@hsenag right... lemme fixup the markup for you... gimme a sec

**Comment by hvr** [comment]
@hsenag fixed (mostly -- except for the boldface markup, but that's something that'll be fixed in hackage soonish), see http://hackage.haskell.org/package/HTTP-4000.3.5/revisions/

I totally missed that markdown syntax was used instead of the proper haddock syntax for the links... btw, this is something that uploading as a package candidate is great for (and cabal 2.0 will default to upload as candidate), as there you can preview how the package description will get rendered

**Comment by hsenag** [comment]
@hvr: Thanks!

**Comment by sjakobi** [comment]
> I totally missed that markdown syntax was used instead of the proper haddock syntax for the links...

Oh, sorry guys. Haddock supports the markdown hyperlink syntax, so I thought that Hackage would support it too… Also thanks for adding the recommendation for http-streams – I wasn't aware of that package!

**Comment by hvr** [comment]
@sjakobi I actually forgot that Haddock learned that syntax (albeit it seems imperfect, as it gets confused about the 2nd occurence  of the markdown url-ref (i.e. it looks like `"http-client (in combination with [http-client-tls](http:/hackage.haskell.orgpackage/http-client-tls) )"` when I try the original `.cabal` revision)

So your expectaction was actually justified; Hackage is supposed to support 99.9% of the markup Haddock supports in `.cabal` files.

**Pull request merged**
