### PR TITLE
Build with GHC 8.0.1 on travis

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
the GHC7.6.3 build fails because the `Cabal` used is old, and don't backtrack: https://travis-ci.org/phadej/scientific/builds/102316993

**Comment by hvr** [comment]
see also comments about `build-tools` usage in #95

**Comment by hvr** [comment]
you may want to rebase... http://hackage.haskell.org/package/HTTP-4000.3.3 was released recently

**Comment by hsenag** [comment]
I've rebased and applied it.

**Pull request closed without merging**
